- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-inspector-grenade
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-managed-non-standalone
        - openstack-tox-functional-py36
        - bifrost-integration-tinyipa-ubuntu-bionic:
            voting: false
        - ironic-inspector-tox-bandit:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-inspector-grenade
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        - ironic-inspector-tempest-managed-non-standalone
        - openstack-tox-functional-py36
