- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-zed-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-inspector-grenade
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        #NOTE(rpittau): temporary non-voting for bugfix release
        #to fix right after
        - ironic-inspector-tempest-managed-non-standalone:
            voting: false
        - openstack-tox-functional-py38
        - bifrost-integration-tinyipa-ubuntu-focal:
            voting: false
        - ironic-inspector-tox-bandit:
            voting: false
    gate:
      jobs:
        - ironic-inspector-grenade
        - ironic-inspector-tempest
        - ironic-inspector-tempest-discovery
        - openstack-tox-functional-py38
